In [3]:
import pandas as pd

# Read the CSV file
from google.colab import drive
drive.mount('/content/drive')
books_data = pd.read_csv("/content/drive/MyDrive/books.csv")

# View the first 5 rows
books_data.head()

MessageError: Error: credential propagation was unsuccessful

In [2]:
numbers = [2, 3, 5, 4]
labels = ['lily', 'rose', 'daisy', 'lotus']
flowers = pd.Series(numbers, index=labels)
flowers['daisy']

NameError: name 'pd' is not defined

In [ ]:
books_data.shape

(5000, 10)

In [ ]:
books_data.describe

<bound method NDFrame.describe of                                                   title  \
0                           The Hunchback of Notre-Dame
1     La Cucina Di Lidia: Recipes and Memories from ...
2                                     Breach of Promise
3                     Brief Interviews with Hideous Men
4     The Killing Dance (Anita Blake  Vampire Hunter...
...                                                 ...
4995                                 The Complete Works
4996                               Shipwreck (Island I)
4997           Every Night Italian: Every Night Italian
4998                                     Go Down  Moses
4999  The Avignon Quintet: Monsieur  Livia  Constanc...

                           author  average_rating         isbn13  \
0                     Victor Hugo            4.00  9780345472427
1     Lidia Matticchio Bastianich            4.14  9780767914222
2                James Scott Bell            4.00  9780310243878
3            David Foster Wallace            3.86  9780349111889
4             Laurell K. Hamilton            4.13  9780425209066
...                           ...             ...            ...
4995          Michel de Montaigne            4.44  9781400040216
4996                Gordon Korman            3.80  9780439023313
4997               Giuliano Hazan            3.79  9780684800288
4998             William Faulkner            3.93  9780679732174
4999             Lawrence Durrell            4.07  9780571225552

     language_code  num_pages  ratings_count  text_reviews_count  \
0            en-US      534.0            140                  22
1            en-GB      288.0             48                   3
2              eng      345.0            368                  36
3              eng      273.0          18335                1155
4            en-US      368.0          59524                 946
...            ...        ...            ...                 ...
4995           eng     1392.0            166                  13
4996           eng        NaN            103                  14
4997           eng      256.0             70                   2
4998           eng      365.0           8289                 370
4999         en-US     1376.0            287                  23

                   publisher  year
0             Modern Library  2004
1            Clarkson Potter  2003
2                  Zondervan  2004
3                     Abacus  2000
4          Berkley Hardcover  2006
...                      ...   ...
4995      Everyman's Library  2003
4996  Scholastic Audio Books  2007
4997                Scribner  2000
4998                 Vintage  1991
4999           Faber & Faber  2004

[5000 rows x 10 columns]>

In [ ]:
books_data.columns

Index(['title', 'author', 'average_rating', 'isbn13', 'language_code',
       'num_pages', 'ratings_count', 'text_reviews_count', 'publisher',
       'year'],
      dtype='object')

In [ ]:
books_data.dtypes

title                  object
author                 object
average_rating        float64
isbn13                  int64
language_code          object
num_pages             float64
ratings_count           int64
text_reviews_count      int64
publisher              object
year                    int64
dtype: object

In [ ]:
books_data[(books_data.year == 2010)]

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
40,The Walking Dead Book One (The Walking Dead #...,Robert Kirkman,4.35,9781582406190,eng,304.0,34751,1346,Image Comics,2010
359,Things: A Story of the Sixties; A Man Asleep,Georges Perec,3.98,9781567921571,eng,221.0,1062,63,David R. Godine Publisher,2010
425,The Gap Into Vision: Forbidden Knowledge (Gap ...,Stephen R. Donaldson,3.99,9780553297607,en-US,480.0,5020,101,Bantam,2010
985,Never Let Me Go,Kazuo Ishiguro,3.82,9781400078776,eng,288.0,380646,22957,Vintage Books,2010
1696,The Unexpected Guest: A Play In Two Acts,Agatha Christie,3.83,9780573014673,eng,100.0,2813,167,Samuel French Ltd,2010
1789,A Short History of Nearly Everything (Illustra...,Bill Bryson,4.21,9780385663557,eng,624.0,28,7,Anchor Canada,2010
2620,The Client,John Grisham,4.00,9780385339087,eng,483.0,367399,1978,Delta,2010
2695,Lord of Light,Roger Zelazny,4.10,9780060567231,eng,296.0,23392,1104,Harper Voyager,2010
2706,Pimsleur German Level 1 CD: [Lessons 1-30],Pimsleur Language Programs,4.23,9780743518369,eng,16.0,58,10,Pimsleur,2010
3079,Tim Burton: Interviews,Kristian Fraga,4.26,9781578067596,eng,192.0,103,7,University Press of Mississippi,2010
3724,Less Than Zero,Bret Easton Ellis,3.58,9780679781493,eng,208.0,55900,2543,Vintage Books,2010
4460,Riddley Walker,Russell Hoban,4.03,9780747559047,eng,236.0,305,44,Bloomsbury,2010
4650,The Beatles' Story on Capitol Records Part Tw...,Bruce Spizer,4.72,9780966264920,eng,264.0,29,0,Four Ninety-Eight Productions,2010
4891,Judy Moody Declares Independence (Judy Moody #6),Megan McDonald,4.08,9780763628000,eng,160.0,3884,132,Candlewick,2010
4914,Earthquake in the Early Morning (Magic Tree Ho...,Mary Pope Osborne,3.94,9780679890706,eng,96.0,6816,227,Random House for Young Readers,2010

In [ ]:
books_data[(books_data.publisher == "DAW") & (books_data.average_rating>4)]

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
71,By the Sword (Valdemar),Mercedes Lackey,4.25,9780886774639,eng,492.0,18531,249,DAW,1991
871,Storm Rising (Valdemar: Mage Storms #2),Mercedes Lackey,4.02,9780886777128,en-US,412.0,10781,86,DAW,1996
1523,Phoenix and Ashes (Elemental Masters #3),Mercedes Lackey,4.01,9780756402723,eng,480.0,6980,229,DAW,2005
1583,To Battle the Gods (Jalav Amazon Warrior #5),Sharon Green,4.07,9780886771287,eng,446.0,87,1,DAW,1986
3726,Oathblood (Valdemar: Vows and Honor #3),Mercedes Lackey,4.06,9780886777739,en-GB,394.0,9786,103,DAW,1998
4367,Joust (Dragon Jousters #1),Mercedes Lackey,4.02,9780756401535,eng,448.0,10113,263,DAW,2004

In [ ]:
books_data[(books_data.num_pages > 500) & (books_data.year > 2010)]

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
2045,Billy Budd Sailor and Other Uncompleted Writi...,Herman Melville,3.11,9780810111141,eng,1016.0,0,0,Northwestern Univ Press,2017
2775,Rick Steves' Europe Through the Back Door,Rick Steves,4.24,9781566918084,eng,808.0,3569,70,Avalon Travel,2017
3075,The Iliad,Homer,3.86,9781904633389,eng,542.0,64,8,Collector's Library,2011
3157,George Washington's Sacred Fire,Peter A. Lillback,4.18,9780978605261,eng,1200.0,694,63,Providence Forum Press,2011
3546,The Will to Power,Friedrich Nietzsche,4.05,9780394704371,eng,575.0,7931,132,Vintage Books,2011

In [ ]:
books_data[(books_data.author == "Agatha Christie")]

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
809,One Two Buckle My Shoe (Hercule Poirot #23),Agatha Christie,3.76,9781572703858,eng,NaN,14388,411,HarperCollins Publishers,2004
850,A Murder Is Announced (Miss Marple #5),Agatha Christie,3.98,9781579126292,eng,288.0,33195,1220,Black Dog & Leventhal Publishers,2006
865,The Listerdale Mystery And Eleven Other Stories,Agatha Christie,3.56,9781572704978,eng,NaN,1824,89,AudioGO,2006
969,Death on the Nile (Hercule Poirot #17),Agatha Christie,4.10,9781579126896,eng,351.0,674,91,Black Dog & Leventhal Publishers,2007
1021,Cards on the Table (Hercule Poirot #15),Agatha Christie,3.92,9780425205952,eng,324.0,25236,1046,Berkley,2005
1396,And Then There Were None,Agatha Christie,4.26,9780312330873,eng,264.0,625767,18785,St. Martin's Press,2004
1433,Hallowe'en Party (Hercule Poirot #39),Agatha Christie,3.66,9780007120680,eng,336.0,20656,1246,Harper,2001
1448,Hickory Dickory Dock (Hercule Poirot #32),Agatha Christie,3.75,9781572705647,eng,196.0,13515,368,AudioGO,2006
1696,The Unexpected Guest: A Play In Two Acts,Agatha Christie,3.83,9780573014673,eng,100.0,2813,167,Samuel French Ltd,2010
2041,The Labours of Hercules (Hercule Poirot #27),Agatha Christie,3.78,9781572704572,eng,9.0,11167,297,AudioGO,2005
2322,Sleeping Murder (Miss Marple #13),Agatha Christie,3.95,9780002317856,eng,242.0,19657,884,Dodd Mead; 1st edition (September 1976),2003
2598,Evil Under the Sun (Hercule Poirot #24),Agatha Christie,3.97,9781579126285,eng,220.0,36334,975,Black Dog & Leventhal Publishers,2006
2966,Murder on the Orient Express (Hercule Poirot ...,Agatha Christie,4.17,9780425200452,eng,322.0,145660,5711,Berkley,2004
3053,A Caribbean Mystery (Miss Marple #10),Agatha Christie,3.80,9780451199928,eng,224.0,18590,770,Signet,2000
3190,Agatha Christie: An Autobiography,Agatha Christie,4.27,9780006353287,eng,560.0,4296,310,HarperCollins,2001
3819,Miss Marple Omnibus Vol. 3 (Murder at the Vica...,Agatha Christie,4.32,9780006499619,eng,688.0,138,5,Harper Collins,1997
3943,Five Complete Miss Marple Novels: The Mirror C...,Agatha Christie,4.39,9780517035801,eng,650.0,116,6,Avenel Books,1990
4402,After the Funeral,Agatha Christie,3.87,9780002310192,eng,251.0,47,4,HarperCollins,2001
4468,The A.B.C. Murders (Hercule Poirot #13),Agatha Christie,4.01,9781579126247,eng,252.0,69806,2470,Black Dog & Leventhal Publishers,2006
4728,They Do It With Mirrors,Agatha Christie,3.76,9781559277587,eng,7.0,2,0,MacMillan Audio,2002
4894,Nemesis (Miss Marple #12),Agatha Christie,3.85,9780451200181,eng,224.0,18896,771,Signet,2000

In [ ]:
books_data[(books_data.average_rating>4.5)&(books_data.ratings_count>10)]

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
13,Fire in the Minds of Men: Origins of the Revol...,James H. Billington,4.54,9780765804716,eng,677.0,96,9,Basic Books,1980
35,The Lord of the Rings: The Art of the Fellowsh...,Gary Russell,4.59,9780618212903,eng,192.0,26153,102,Houghton Mifflin Harcourt,2002
54,Collected Stories III: One Night in Brazil to ...,Isaac Bashevis Singer,4.61,9781931082631,eng,915.0,23,4,Library of America,2004
83,Collected Essays: Notes of a Native Son / Nobo...,James Baldwin,4.61,9781883011529,eng,869.0,1495,75,Library of America (NY),1998
200,Eva Hesse Drawing,Catherine de Zegher,4.55,9780300116182,eng,344.0,51,6,Yale University Press,2006
334,The Price of the Ticket: Collected Nonfiction ...,James Baldwin,4.70,9780312643065,eng,712.0,404,30,St. Martin's Press,1985
457,The Shawshank Redemption: The Shooting Script,Frank Darabont,4.64,9781557042460,eng,184.0,2406,29,Newmarket Press,2004
613,Nausicaä of the Valley of the Wind Vol. 5 (Na...,Hayao Miyazaki,4.61,9781591164128,eng,151.0,1904,28,VIZ Media,2004
650,The J.R.R. Tolkien Companion and Guide Volume...,Christina Scull,4.51,9780618391028,eng,1002.0,40,2,Houghton Mifflin Harcourt,2006
808,Lego Star Wars: Prima Official Game Guide,Michael Littlefield,4.62,9780761554912,eng,128.0,27,2,Prima Games,2006
1000,The Fate of Reason: German Philosophy from Kan...,Frederick C. Beiser,4.52,9780674295032,eng,410.0,118,8,Harvard University Press,1993
1008,The Complete Maus,Art Spiegelman,4.55,9780141014081,eng,296.0,111475,5966,Penguin Books,2003
1024,A History of the Life Sciences,Lois N. Magner,4.53,9780824708245,en-US,514.0,15,2,CRC Press,2002
1033,The Valley of Vision: A Collection of Puritan ...,Arthur Bennett,4.54,9780851512280,eng,223.0,9476,247,Banner of Truth,1975
1057,The Power Broker: Robert Moses and the Fall of...,Robert A. Caro,4.51,9780394720241,eng,1344.0,11208,1237,Vintage,1975
1079,Cook's Illustrated 1995 (Cook's Illustrated An...,Cook's Illustrated Magazine,4.53,9780964017931,eng,232.0,15,1,Cook's Illustrated,1995
1124,The Complete Novels,Jane Austen,4.55,9780140259445,eng,1344.0,21633,351,Penguin,1996
1280,The Return of the King (The Lord of the Rings ...,J.R.R. Tolkien,4.53,9780965307796,eng,440.0,202,10,Quality Paperback Book Club,2001
1285,The Total Library: Non-Fiction 1922-1986,Jorge Luis Borges,4.52,9780141183022,eng,560.0,164,17,Penguin Books Ltd,2001
1578,Harry Potter and the Goblet of Fire (Harry Pot...,J.K. Rowling,4.56,9780747546245,eng,636.0,18754,906,Bloomsbury,2000
1648,Nausicaä of the Valley of the Wind Vol. 6 (Na...,Hayao Miyazaki,4.62,9781591163541,eng,159.0,1776,33,VIZ Media,2004
1779,The World's First Love: Mary Mother of God,Fulton J. Sheen,4.59,8987059752,en-US,276.0,641,63,Ignatius Press,1996
2168,混血王子的背叛 (哈利波特 #6),J.K. Rowling,4.57,9789573321743,NaN,735.0,75,0,皇冠文化出版有限公司,2005
2241,Animal: The Definitive Visual Guide to the Wor...,David Burnie,4.51,9780756616342,eng,624.0,570,17,DK,2005
2264,The Complete Novels,Jane Austen,4.55,9780143039501,eng,1278.0,425,39,Penguin Classics,2006
2354,The Life and Games of Mikhail Tal,Mikhail Tal,4.52,9781857442021,eng,496.0,442,24,Everyman Chess,1997
2480,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling,4.56,9780747573623,eng,480.0,3141,140,Bloomsbury UK,2008
2495,The Lord of the Rings / The Hobbit,J.R.R. Tolkien,4.59,9780007144082,eng,1600.0,141,5,Collins Modern Classics,2002
2513,Shahnameh: The Persian Book of Kings,Abolqasem Ferdowsi,4.51,9780143104933,eng,886.0,246,21,Penguin,2007
2553,Coffin: The Art of Vampire Hunter D,Yoshitaka Amano,4.58,9781595820617,eng,199.0,596,16,Dark Horse Books,2006
2580,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling,4.78,9780439682589,eng,2690.0,41428,164,Scholastic,2004
2641,Collected Fictions,Jorge Luis Borges,4.58,9780140286809,eng,565.0,18874,791,Penguin Classics Deluxe Edition,1999
2676,Saul Steinberg: Illuminations,Saul Steinberg,4.51,9780300115864,eng,288.0,39,5,Yale University Press,2006
2759,Existential Meditation,Simon Cleveland,4.91,9781411665309,eng,100.0,11,3,Lulu.com,2005
2789,The Feynman Lectures on Physics Vol 2,Richard P. Feynman,4.62,9780805390476,eng,512.0,17,2,Pearson Education,2005
2800,Fullmetal Alchemist Vol. 9 (Fullmetal Alchemi...,Hiromu Arakawa,4.57,9781421504605,eng,192.0,9013,153,VIZ Media LLC,2006
2872,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling,4.57,9780439785969,eng,652.0,2095690,27591,Scholastic Inc.,2006
2874,The Life and Times of Scrooge McDuck,Don Rosa,4.67,9780911903966,eng,266.0,2467,149,Gemstone Publishing,2005
2930,Nausicaä de la vallée du vent tome 3,Hayao Miyazaki,4.56,9782723433914,NaN,144.0,32,3,Glénat,2001
2938,The Lord of the Rings: The Return of the King ...,Jude Fisher,4.59,9780007116263,eng,72.0,26,3,HarperCollins,2003
2950,The Wake (The Sandman #10),Neil Gaiman,4.52,9781563892875,eng,191.0,37038,767,Vertigo,1999
3293,It's a Magical World (Calvin and Hobbes #11),Bill Watterson,4.76,9780836221367,eng,176.0,23875,303,Andrews McMeel Publishing,1996
3497,Fullmetal Alchemist Vol. 12 (Fullmetal Alchem...,Hiromu Arakawa,4.60,9781421508399,eng,192.0,7480,119,VIZ Media LLC,2007
3571,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling,4.56,9780439655484,eng,435.0,2339585,36325,Scholastic Inc.,2004
3633,Harry Potter Collection (Harry Potter #1-6),J.K. Rowling,4.73,9780439827607,eng,3342.0,28242,808,Scholastic,2005
3840,The Lord of the Rings: Weapons and Warfare,Chris Smith,4.53,9780618391004,eng,218.0,19822,46,Houghton Mifflin Harcourt,2003
3947,Homicidal Psycho Jungle Cat (Calvin and Hobbes...,Bill Watterson,4.72,9780836217698,eng,176.0,15365,290,Andrews McMeel Publishing,1994
4058,The Return of the King (The Lord of the Rings ...,J.R.R. Tolkien,4.53,9780007171996,eng,554.0,265,5,HarperCollins Publishers Ltd,2003
4076,Herbert the Timid Dragon,Mercer Mayer,4.62,9780307114631,eng,48.0,23,4,Western Publishing Company Golden Books,1991
4147,The More Than Complete Hitchhiker's Guide (Hit...,Douglas Adams,4.58,9780681403222,en-US,624.0,433,34,Longmeadow Press,1989
4180,Fullmetal Alchemist Vol. 4 (Fullmetal Alchemi...,Hiromu Arakawa,4.55,9781591169291,eng,200.0,10752,294,VIZ Media LLC,2005
4277,The Beatles Diary Vol 1: From Liverpool to Lo...,Keith Badman,4.56,9780711983083,eng,376.0,13,0,Omnibus Press,2001
4371,Harry Potter und der Gefangene von Askaban (Ha...,J.K. Rowling,4.56,9783895849619,ger,13.0,313,8,Dhv der Hörverlag,2002
4391,Looking East,Steve McCurry,4.55,9780714846378,eng,124.0,83,8,Phaidon Press,2006
4486,Tal-Botvinnik 1960,Mikhail Tal,4.55,9781888690088,eng,220.0,161,12,Russell Enterprises,2001
4637,Fullmetal Alchemist Vol. 6 (Fullmetal Alchemi...,Hiromu Arakawa,4.58,9781421503196,eng,200.0,10052,201,VIZ Media LLC,2006
4650,The Beatles' Story on Capitol Records Part Tw...,Bruce Spizer,4.72,9780966264920,eng,264.0,29,0,Four Ninety-Eight Productions,2010
4911,In Search of Lost Time Vol. 2: Within a Buddi...,Marcel Proust,4.57,9781841598970,eng,888.0,48,1,Everyman's Library,2001
4953,Complete Guide to the Bible,Reader's Digest Association,4.58,9780762100736,eng,448.0,12,3,Readers Digest,1998

In [ ]:
books_data[(books_data.>4.5)&(books_data.ratings_count>10)]

In [ ]:
books_data.loc[books_data['language_code'] == 'eng', 'average_rating'].mean()

3.931142857142857

In [ ]:
books_data.loc[:,'average_rating'].mean()

3.9319319999999998

In [ ]:
books_data.loc[:,'num_pages'].mean()

341.0940205355345

In [ ]:
books_data.loc[:,'num_pages'].max()

3342.0

In [ ]:
books_data.loc[:,'num_pages'].max()

In [ ]:
books_data.loc[:,'num_pages'].mode()

0    288.0
Name: num_pages, dtype: float64

In [ ]:
books_data.iloc[0:5,1:4]

                        author  average_rating         isbn13
0                  Victor Hugo            4.00  9780345472427
1  Lidia Matticchio Bastianich            4.14  9780767914222
2             James Scott Bell            4.00  9780310243878
3         David Foster Wallace            3.86  9780349111889
4          Laurell K. Hamilton            4.13  9780425209066

In [ ]:
books_data.loc[[1,4],['language_code','num_pages','ratings_count']]

  language_code  num_pages  ratings_count
1         en-GB      288.0             48
4         en-US      368.0          59524

In [ ]:
books_data[(books_data.language_code == "spa") & (books_data.year > 2000)]

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
21,Los funerales de la Mamá Grande,Gabriel García Márquez,3.78,9780307350329,spa,160.0,4694,133,Plaza y Janes,2006
53,La Emperatriz tras el velo (Trilogía Taj Mahal...,Indu Sundaresan,4.04,9788425337604,spa,382.0,2,1,Grijalbo Mondadori Sa,2003
69,La casa de los espíritus,Isabel Allende,4.23,9780060951306,spa,454.0,608,38,HarperCollins Espanol,2001
93,Ya Sé Que Te Quiero,Billy Crystal,4.19,9780060845988,spa,40.0,0,0,Rayo,2006
107,Secretos De Familia,Julia Glass,3.57,9788496525030,spa,528.0,0,1,Puzzle-Roca,2006
...,...,...,...,...,...,...,...,...,...,...
4804,Muerte Blanca,Clive Cussler,3.91,9780307343260,spa,421.0,2,0,Debolsillo,2005
4832,Entrevista con el vampiro (Crónicas vampíricas...,Anne Rice,3.99,9788466616201,spa,463.0,1307,93,Ediciones B,2005
4890,Isabel: Princesa De Castilla España 1466,Carolyn Meyer,3.71,9788478886746,spa,184.0,8,0,Salamandra,2001
4907,Ve perro ¡Ve!,P.D. Eastman,4.09,9780375823619,spa,24.0,33,2,Random House Para Ninos,2003
4951,El librero de Kabul,Åsne Seierstad,3.76,9789706519245,spa,285.0,112,18,Grupo Océano,2004

In [ ]:
books_data[(books_data.author == "Agatha Christie")]

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
809,One Two Buckle My Shoe (Hercule Poirot #23),Agatha Christie,3.76,9781572703858,eng,NaN,14388,411,HarperCollins Publishers,2004
850,A Murder Is Announced (Miss Marple #5),Agatha Christie,3.98,9781579126292,eng,288.0,33195,1220,Black Dog & Leventhal Publishers,2006
865,The Listerdale Mystery And Eleven Other Stories,Agatha Christie,3.56,9781572704978,eng,NaN,1824,89,AudioGO,2006
969,Death on the Nile (Hercule Poirot #17),Agatha Christie,4.10,9781579126896,eng,351.0,674,91,Black Dog & Leventhal Publishers,2007
1021,Cards on the Table (Hercule Poirot #15),Agatha Christie,3.92,9780425205952,eng,324.0,25236,1046,Berkley,2005
1396,And Then There Were None,Agatha Christie,4.26,9780312330873,eng,264.0,625767,18785,St. Martin's Press,2004
1433,Hallowe'en Party (Hercule Poirot #39),Agatha Christie,3.66,9780007120680,eng,336.0,20656,1246,Harper,2001
1448,Hickory Dickory Dock (Hercule Poirot #32),Agatha Christie,3.75,9781572705647,eng,196.0,13515,368,AudioGO,2006
1696,The Unexpected Guest: A Play In Two Acts,Agatha Christie,3.83,9780573014673,eng,100.0,2813,167,Samuel French Ltd,2010
2041,The Labours of Hercules (Hercule Poirot #27),Agatha Christie,3.78,9781572704572,eng,9.0,11167,297,AudioGO,2005
2322,Sleeping Murder (Miss Marple #13),Agatha Christie,3.95,9780002317856,eng,242.0,19657,884,Dodd Mead; 1st edition (September 1976),2003
2598,Evil Under the Sun (Hercule Poirot #24),Agatha Christie,3.97,9781579126285,eng,220.0,36334,975,Black Dog & Leventhal Publishers,2006
2966,Murder on the Orient Express (Hercule Poirot ...,Agatha Christie,4.17,9780425200452,eng,322.0,145660,5711,Berkley,2004
3053,A Caribbean Mystery (Miss Marple #10),Agatha Christie,3.80,9780451199928,eng,224.0,18590,770,Signet,2000
3190,Agatha Christie: An Autobiography,Agatha Christie,4.27,9780006353287,eng,560.0,4296,310,HarperCollins,2001
3819,Miss Marple Omnibus Vol. 3 (Murder at the Vica...,Agatha Christie,4.32,9780006499619,eng,688.0,138,5,Harper Collins,1997
3943,Five Complete Miss Marple Novels: The Mirror C...,Agatha Christie,4.39,9780517035801,eng,650.0,116,6,Avenel Books,1990
4402,After the Funeral,Agatha Christie,3.87,9780002310192,eng,251.0,47,4,HarperCollins,2001
4468,The A.B.C. Murders (Hercule Poirot #13),Agatha Christie,4.01,9781579126247,eng,252.0,69806,2470,Black Dog & Leventhal Publishers,2006
4728,They Do It With Mirrors,Agatha Christie,3.76,9781559277587,eng,7.0,2,0,MacMillan Audio,2002
4894,Nemesis (Miss Marple #12),Agatha Christie,3.85,9780451200181,eng,224.0,18896,771,Signet,2000